config/routes.rb
Clippping::Application.routes.draw do
	
  resources :categories do
    post 'by_entity', on: :collection
  end
	
  resources :shippings do
		post 'check_source_url', on: :collection
		post 'news_template', on: :collection
		post 'send_mails/:shipping_id', action: 'send_mails', as: 'send_mails', on: :collection
		post 'send_demo/:shipping_id', action: 'send_demo', as: 'send_demo', on: :collection
		get 'new/:entity_id', action: 'new', as: 'new_with_entity', on: :collection
  end
  
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'iniciar_sesion', :sign_out => 'cerrar_sesion', :password => 'secret', :confirmation => 'verificar' }
	
	resources :users
	resources :entities
	resources :receivers

  root :to => "home#index"
	
	
	constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.is_admin? }
	constraints constraint do
		require 'sidekiq/web'
	  mount Sidekiq::Web => '/sidekiq'
	end

end

app/models/shipping.rb
class Shipping < ActiveRecord::Base
	has_and_belongs_to_many :receivers
	has_many :publications, dependent: :delete_all
	has_many :source_covers, dependent: :delete_all
	
	belongs_to :user
	belongs_to :entity
	
	accepts_nested_attributes_for :publications, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :source_covers, reject_if: :all_blank, allow_destroy: true
	
	attr_accessible :name, :entity_id, :publications_attributes, :source_covers_attributes, :individuals
	
	validates_presence_of :name
	validates_presence_of :entity_id
end

app/controllers/shippings_controller.rb
# encoding: UTF-8

class ShippingsController < ApplicationController
  before_filter :authenticate_user!
	
	# GET /shippings
  # GET /shippings.json
  def index
		
		@selected = params[:entity];
		unless current_user.is_admin?
			@entities = Entity.where(id: current_user.entities)
		else
			@entities = Entity.all
		end
		
		@selected = @entities.first.id if @selected.nil?
		
		@shippings = Shipping.includes([:entity, :user]).where(entity_id: @selected).order('id DESC').page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shippings }
    end
  end

  # GET /shippings/1
  # GET /shippings/1.json
  def show
    @shipping = Shipping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shipping }
    end
  end

  # GET /shippings/new
  # GET /shippings/new.json
  def new
    @shipping = Shipping.new
		@entity = Entity.find(params[:entity_id])
		@categories = @entity.categories
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shipping }
    end
  end

  # GET /shippings/1/edit
  def edit
    @shipping = Shipping.find(params[:id])
		@entity = @shipping.entity
		@categories = Category.by_entity(@shipping.entity_id)
  end

  # POST /shippings
  # POST /shippings.json
  def create
    @shipping = Shipping.new(params[:shipping])
		@shipping.name = "#{"%02d" % Time.now.day}-#{"%02d" % Time.now.month}-#{Time.now.year.to_s}" if @shipping.name.empty?
		@shipping.user = current_user
    respond_to do |format|
      if @shipping.save
        format.html { redirect_to @shipping, notice: 'Shipping was successfully created.' }
        format.json { render json: @shipping, status: :created, location: @shipping }
      else
				@entity = @shipping.entity
				@categories = Category.by_entity(@shipping.entity_id)
				
        format.html { render action: "new" }
        format.json { render json: @shipping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shippings/1
  # PUT /shippings/1.json
  def update
    @shipping = Shipping.find(params[:id])

    respond_to do |format|
      if @shipping.update_attributes(params[:shipping])
        format.html { redirect_to @shipping, notice: 'Shipping was successfully updated.' }
        format.json { head :no_content }
      else
				@entity = @shipping.entity
				@categories = Category.by_entity(@shipping.entity_id)
				
        format.html { render action: "edit" }
        format.json { render json: @shipping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shippings/1
  # DELETE /shippings/1.json
  def destroy
    @shipping = Shipping.find(params[:id])
    @shipping.destroy

    respond_to do |format|
      format.html { redirect_to shippings_url }
      format.json { head :no_content }
    end
  end

	def check_source_url
		require 'open-uri'
		require 'nokogiri'
		
		response = {}
		uri = URI(params[:url])
		#url: "#{uri.scheme}://#{uri.host}"
		source = Source.where("POSITION(url IN ?) <> 0", "#{uri.scheme}://#{uri.host}")
		
		if source.present?
			response[:source] = source[0].name
			response[:source_url] = "#{uri.scheme}://#{uri.host}"
			
			doc = Nokogiri::HTML(open(params[:url]).read)
			
		  doc.css(source[0].title_reg).each do |elem|
		    response[:title] = elem.content.strip
		  end
			
		  doc.css(source[0].short_content_reg).each do |elem|
		    response[:short_content] = elem.content.strip
		  end
		end
		
		respond_to do |format|
			format.json {render json: response}
		end
	end
	
	def send_demo
		shipping = Shipping.find(params[:shipping_id])
		ReceiverMailer.clipping_email(shipping, current_user.email).deliver
    #SenderWorker.perform_async(shipping, current_user.email)
    flash[:notice] = 'El mail de demostración fue enviado.'
		redirect_to action: 'index', entity: shipping.entity_id
	end
	
	def send_mails
    shipping = Shipping.find(params[:shipping_id])
		shipping.entity.receivers.each do |receiver|
			ReceiverMailer.clipping_email(shipping, receiver.mail_style).deliver
      #SenderWorker.perform_async(shipping, current_user.email)
			shipping.receivers << receiver
		end
    shipping.individuals.split(",").each do |individual|
      ReceiverMailer.clipping_email(shipping, individual).deliver
    end
    flash[:notice] = 'Los mails fueron enviados a los recipientes.'
		redirect_to action: 'index', entity: shipping.entity_id
	end
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/shippings/_categories_list.html.haml
%ul
  - categories.each do |category|
    %li
      %h3{id: "category_#{category.id}"}
        = category.name
        =link_to_add_association 'Agregar', f, :publications, :'data-association-insertion-node' => "#category_#{category.id}", :'data-association-insertion-position' => 'after'          
      =f.simple_fields_for :publications, Publication.where(category_id: category.id, shipping_id: shipping_id) do |publication|
        =render "publication_fields", f: publication, publication_fields: category.id

app/views/shippings/_form.html.haml
= simple_form_for @shipping, :html => { :class => 'form-horizontal' }, :wrapper => :bootstrap do |f|
  = f.input :name, hint: "Si va vacío, por defecto se carga como nombre la fecha del día"
  = f.input :individuals, hint: "Mails separados por comas para envios ocacionales. Ej. pepe@gmail.com,juan@gmail.com"
  = f.input :entity_id do
    %h4{style: "position:relative; top: -5px"}= @entity.name
    =f.input_field :entity_id, as: :hidden, value: @entity.id
  %h3
    = Category.model_name.human.pluralize
  %hr
  .control-group{id:"category"}
    =render "categories_list", categories: @categories, f: f, shipping_id: @shipping.id
  %h3 Anuncios
  .control-group{id:"source_covers"}
    =f.simple_fields_for :source_covers do |cover|
      = render 'source_cover_fields', :f => cover
    .links
      = link_to_add_association 'Agregar portada', f, :source_covers
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), shippings_path, :class => 'btn'

app/views/shippings/_publication_fields.html.haml
.nested-fields
  .row
    .span4
      = f.input_field :category_id, as: :hidden, value: publication_fields
      = f.input_field :source, as: :hidden
      = f.input_field :source_url, as: :hidden
      = f.input :url, placeholder: "Url de la noticia", input_html: {class: "get_url_data"}
    .span4
      = f.input :title, label: "Titulo", placeholder: "Titulo de la noticia"
  .row
    .span8
      = f.input :short_content, as: :text, placeholder: "Contenido corto (Copete)", input_html: {style: 'width: 600px', rows: 5}, label: "Copete"
  .row
    .span6
      &nbsp;
      .date_time.input-append.date
        = f.input :published_at, label: "Fecha de publicación" do
          =f.input_field :published_at, as: :string, placeholder: "Fecha de publicación", :'data-format' => "yyyy-MM-dd"
          %span.add-on
            %i{:'data-time-icon' => 'icon-time', :'data-date-icon' => 'icon-calendar'}
    .span2= link_to_remove_association "Eliminar", f
  .row
    .span8 &nbsp;

app/views/shippings/_source_cover_fields.html.haml
.nested-fields
  .row
    .span8
      = f.input :image_cover, as: :file
      = f.input :source_id, collection: Source.all
    .span4
      %span= link_to_remove_association "Eliminar", f

app/views/shippings/edit.html.haml
- content_for :js do
  = javascript_include_tag "cocoon"
  = javascript_include_tag "shippings"
  = javascript_include_tag "bootstrap-datetimepicker"
  = javascript_include_tag "locales/bootstrap-datetimepicker.es"
- model_class = Shipping
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/shippings/index.html.haml
- content_for :js do
  = javascript_include_tag "shippings"
- model_class = Shipping
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
  %h3
    Filtrar por:
  =select_tag "filter_by_entity", options_from_collection_for_select(@entities, "id", "name", @selected)
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      - if current_user.is_admin
        %th= model_class.human_attribute_name(:user_id)
        %th= model_class.human_attribute_name(:entity_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @shippings.each do |shipping|
      %tr
        %td= link_to shipping.id, shipping_path(shipping)
        %td= shipping.name
        - if current_user.is_admin
          %td= shipping.user.name
          %td= shipping.entity.name
        %td=l shipping.created_at, format: :short
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_shipping_path(shipping), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), shipping_path(shipping), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
          = link_to t('.send', :default => t("helpers.links.send")), send_mails_shippings_path(shipping), :method => 'post', :class => 'btn btn-mini btn-success'
          = link_to t('.send_demo', :default => t("helpers.links.send_demo")), send_demo_shippings_path(shipping), :method => 'post', :class => 'btn btn-mini'

= paginate @shippings, window: 2

= link_to t('.new', :default => t("helpers.links.new")), new_with_entity_shippings_path(@selected), :class => 'btn btn-primary'

app/views/shippings/new.html.haml
- content_for :js do
  = javascript_include_tag "cocoon"
  = javascript_include_tag "shippings"
  = javascript_include_tag "bootstrap-datetimepicker"
  = javascript_include_tag "locales/bootstrap-datetimepicker.es"
- model_class = Shipping
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/shippings/show.html.haml
- model_class = Shipping
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @shipping.name
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @shipping.user_id
%p
  %strong= model_class.human_attribute_name(:entity_id) + ':'
  %br
  = @shipping.entity_id
%p
  %strong= model_class.human_attribute_name(:total) + ':'
  %br
  = @shipping.total
%p
  %strong= model_class.human_attribute_name(:processed) + ':'
  %br
  = @shipping.processed
%p
  %strong= model_class.human_attribute_name(:begin_at) + ':'
  %br
  = @shipping.begin_at
%p
  %strong= model_class.human_attribute_name(:end_at) + ':'
  %br
  = @shipping.end_at

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), shippings_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_shipping_path(@shipping), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), shipping_path(@shipping), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'