config/routes.rb
Clippping::Application.routes.draw do
	
  resources :categories do
    post 'by_entity', on: :collection
  end
	
  resources :shippings do
		post 'check_source_url', on: :collection
		post 'news_template', on: :collection
		post 'send_mails/:shipping_id', action: 'send_mails', as: 'send_mails', on: :collection
		post 'send_demo/:shipping_id', action: 'send_demo', as: 'send_demo', on: :collection
		get 'new/:entity_id', action: 'new', as: 'new_with_entity', on: :collection
  end
  
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'iniciar_sesion', :sign_out => 'cerrar_sesion', :password => 'secret', :confirmation => 'verificar' }
	
	resources :users
	resources :entities
	resources :receivers

  root :to => "home#index"
	
	
	constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.is_admin? }
	constraints constraint do
		require 'sidekiq/web'
	  mount Sidekiq::Web => '/sidekiq'
	end

end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
	has_and_belongs_to_many :shippings
	belongs_to :entity
	
	attr_accessible :email, :name, :entity_id
	
	validates_presence_of :name, :on => :create
	validates_presence_of :entity_id, :on => :create
	
	def mail_style
    if self.name.empty?
      self.email
    else
      "\"#{self.name}\" <#{self.email}>"
    end
	end
end

app/controllers/receivers_controller.rb
# encoding: UTF-8

class ReceiversController < ApplicationController
  before_filter :authenticate_user!
	before_filter :load_entities, only: [:index, :new, :edit]
	
	def load_entities
		unless current_user.is_admin?
			@entities = Entity.where(id: current_user.entities)
		else
			@entities = Entity.all
		end
		
	end
	
  # GET /receivers
  # GET /receivers.json
  def index
		
		@selected = params[:entity];
		
		if @selected.nil?
			@receivers = Receiver.includes(:entity).where(entity_id: @entities.first.id).page(params[:page])
		else
			@receivers = Receiver.includes(:entity).where(entity_id: @selected).page(params[:page])
		end
		
		redirect_to categories_path if @entities.map {|o| o.id }.include? params[:entity]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receivers }
    end
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
    @receiver = Receiver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receiver }
    end
  end

  # GET /receivers/new
  # GET /receivers/new.json
  def new
    @receiver = Receiver.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receiver }
    end
  end

  # GET /receivers/1/edit
  def edit
    @receiver = Receiver.find(params[:id])
  end

  # POST /receivers
  # POST /receivers.json
  def create
    @receiver = Receiver.new(params[:receiver])

    respond_to do |format|
      if @receiver.save
        format.html { redirect_to @receiver, notice: 'Receiver was successfully created.' }
        format.json { render json: @receiver, status: :created, location: @receiver }
      else
        format.html { render action: "new" }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receivers/1
  # PUT /receivers/1.json
  def update
    @receiver = Receiver.find(params[:id])

    respond_to do |format|
      if @receiver.update_attributes(params[:receiver])
        format.html { redirect_to @receiver, notice: 'Receiver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    @receiver = Receiver.find(params[:id])
    @receiver.destroy

    respond_to do |format|
      format.html { redirect_to receivers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/views/receivers/_form.html.haml
= simple_form_for @receiver, :html => { :class => 'form-horizontal' } do |f|
  = f.input :email
  = f.input :name
  = f.input :entity_id, collection: @entities, prompt: "Seleccione una entidad..."
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), receivers_path, :class => 'btn'

app/views/receivers/edit.html.haml
- model_class = Receiver
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/receivers/index.html.haml
- content_for :js do
  = javascript_include_tag "receivers"
- model_class = Receiver
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
  %h3
    Filtrar por:
  =select_tag "filter_by_entity", options_from_collection_for_select(@entities, "id", "name", @selected)
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:entity_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @receivers.each do |receiver|
      %tr
        %td= link_to receiver.id, receiver_path(receiver)
        %td= receiver.email
        %td= receiver.name
        %td= receiver.entity.name
        %td=l receiver.created_at, format: :short
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_receiver_path(receiver), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), receiver_path(receiver), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= paginate @receivers, window: 2

= link_to t('.new', :default => t("helpers.links.new")), new_receiver_path, :class => 'btn btn-primary'

app/views/receivers/new.html.haml
- model_class = Receiver
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/receivers/show.html.haml
- model_class = Receiver
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @receiver.email
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @receiver.name
%p
  %strong= model_class.human_attribute_name(:entity_id) + ':'
  %br
  = @receiver.entity_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), receivers_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_receiver_path(@receiver), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), receiver_path(@receiver), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'