config/routes.rb
Clippping::Application.routes.draw do
	
  resources :categories do
    post 'by_entity', on: :collection
  end
	
  resources :shippings do
		post 'check_source_url', on: :collection
		post 'news_template', on: :collection
		post 'send_mails/:shipping_id', action: 'send_mails', as: 'send_mails', on: :collection
		post 'send_demo/:shipping_id', action: 'send_demo', as: 'send_demo', on: :collection
		get 'new/:entity_id', action: 'new', as: 'new_with_entity', on: :collection
  end
  
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'iniciar_sesion', :sign_out => 'cerrar_sesion', :password => 'secret', :confirmation => 'verificar' }
	
	resources :users
	resources :entities
	resources :receivers

  root :to => "home#index"
	
	
	constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.is_admin? }
	constraints constraint do
		require 'sidekiq/web'
	  mount Sidekiq::Web => '/sidekiq'
	end

end

app/models/entity.rb
class Entity < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :shippings, dependent: :delete_all
	has_many :receivers, dependent: :delete_all
	has_many :categories, dependent: :delete_all
	
  attr_accessible :name, :avatar
	
	validates_presence_of :name, :on => :create
  
  mount_uploader :avatar, EntityAvatarUploader
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
	before_filter :authenticate_user!
	before_filter :user_authorization
  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entities }
    end
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
    @entity = Entity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entity }
    end
  end

  # GET /entities/new
  # GET /entities/new.json
  def new
    @entity = Entity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entity }
    end
  end

  # GET /entities/1/edit
  def edit
    @entity = Entity.find(params[:id])
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(params[:entity])

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render json: @entity, status: :created, location: @entity }
      else
        format.html { render action: "new" }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entities/1
  # PUT /entities/1.json
  def update
    @entity = Entity.find(params[:id])

    respond_to do |format|
      if @entity.update_attributes(params[:entity])
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity = Entity.find(params[:id])
		@entity.users.clear
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.haml
= simple_form_for @entity, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :avatar, as: :file
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), entities_path, :class => 'btn'

app/views/entities/edit.html.haml
- model_class = Entity
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/entities/index.html.haml
- model_class = Entity
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @entities.each do |entity|
      %tr
        %td= link_to entity.id, entity_path(entity)
        %td= entity.name
        %td=l entity.created_at, format: :short
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_entity_path(entity), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), entity_path(entity), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_entity_path, :class => 'btn btn-primary'

app/views/entities/new.html.haml
- model_class = Entity
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/entities/show.html.haml
- model_class = Entity
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @entity.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), entities_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_entity_path(@entity), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), entity_path(@entity), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'