config/routes.rb
Clippping::Application.routes.draw do
	
  resources :categories do
    post 'by_entity', on: :collection
  end
	
  resources :shippings do
		post 'check_source_url', on: :collection
		post 'news_template', on: :collection
		post 'send_mails/:shipping_id', action: 'send_mails', as: 'send_mails', on: :collection
		post 'send_demo/:shipping_id', action: 'send_demo', as: 'send_demo', on: :collection
		get 'new/:entity_id', action: 'new', as: 'new_with_entity', on: :collection
  end
  
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'iniciar_sesion', :sign_out => 'cerrar_sesion', :password => 'secret', :confirmation => 'verificar' }
	
	resources :users
	resources :entities
	resources :receivers

  root :to => "home#index"
	
	
	constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.is_admin? }
	constraints constraint do
		require 'sidekiq/web'
	  mount Sidekiq::Web => '/sidekiq'
	end

end

app/views/layouts/_menu.html.haml
.navbar.navbar-fluid-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand(href="#") Clippping
      .container.nav-collapse
        %ul.nav
          %li.dropdown
            =link_to "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown" do
              =t("menu.config.title")
              =raw("<b class='caret'></b>")
            %ul.dropdown-menu
              %li= link_to t("menu.config.submenu.categories"), categories_path
              %li= link_to t("menu.config.submenu.receivers"), receivers_path
              - if current_user.is_admin
                %li= link_to t("menu.config.submenu.users"), users_path
                %li= link_to t("menu.config.submenu.entities"), entities_path
          %li.dropdown
            =link_to "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown" do
              =t("menu.shipping.title")
              =raw("<b class='caret'></b>")
            %ul.dropdown-menu
              %li=link_to t("menu.shipping.submenu.new"), shippings_path
        .pull-right
          %ul.nav.pull-right
            %li.dropdown
              %a.dropdown-toggle{href: "#", :'data-toggle' => 'dropdown'}
                = current_user.name
                %b.caret
              %ul.dropdown-menu
                %li= link_to "salir", destroy_user_session_path, :method => :delete

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Clippping"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="/assets/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="/assets/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="/assets/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="/assets/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="/assets/favicon.ico" rel="shortcut icon")
    

  %body
    = render "layouts/menu"
    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
        .span9
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Social Cherry 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield(:js)

app/views/layouts/login.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Clippping"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body{style: "padding: 10px;margin: 10px"}
    .container-fluid
      .row-fluid
        .span6.offset3
          = yield
    
      %footer
        %p &copy; Social Cherry 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"